#ddev-generated
services:
  lazydocker:
    build:
      context: https://github.com/jesseduffield/lazydocker.git
      args:
        BASE_IMAGE_BUILDER: golang
        GOARCH: amd64
        GOARM:
    image: lazyteam/lazydocker
    container_name: ddev-${DDEV_PROJECT}-lazydocker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./lazydocker:/.config/jesseduffield/lazydocker
    stdin_open: true
    tty: true
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
