#ddev-generated
services:
  lazydocker:
    build:
      context: ./lazydocker
    container_name: ddev-${DDEV_PROJECT}-lazydocker
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ./lazydocker/config:/.config/jesseduffield/lazydocker
    stdin_open: true
    tty: true
    environment:
      - DDEV_PROJECT=${DDEV_PROJECT}
      - TERM=xterm-256color
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    healthcheck:
      test: ["CMD", "test", "-S", "/var/run/docker.sock"]
      interval: 10s
      timeout: 3s
      retries: 3